export { detectRedFlags } from './detect'
export { reframeMessage } from './reframe'
export { checkRelationshipHealth } from './health-check'
export { sanitizeForPrompt } from './sanitize'
export { RELATIONSHIP_CONTEXTS } from './relationships'
export type { RelationshipContext } from './relationships'
